M48
; DRILL file {KiCad 6.0.5} date Sun 09 Oct 2022 08:24:41 AM AEDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-09T08:24:41+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0670
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1350
%
G90
G05
T1
X0.6942Y-0.7253
X0.6942Y-1.2923
X1.3169Y-0.7253
X1.3169Y-1.2923
T2
X0.7835Y-1.0
X1.2165Y-1.0
T3
X1.0Y-0.7657
X1.1969Y-0.8524
T4
X1.0Y-1.0
T0
M30
